// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>


float Qos0;
float Qos1;
float Qos2;

void initProperties(){

  ArduinoCloud.addProperty(Qos0, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(Qos1, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(Qos2, READ, ON_CHANGE, NULL);

}

////////////////////////////ATTENTION!!!////////////////////////////////
// ATTENTION: No device is currently associated to this Thing,        //
// hence the Connection Handler code could not be generated           //
// Please associate an existing or new device or manually create your //
// instance of Connection Handler                                     //
// Eg.                                                                // 
// WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);   //
////////////////////////////////////////////////////////////////////////

#error "No device is currently associated to this Thing, hence the Connection Handler code could not be generated"
